# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a9691ece5be43c71e7fc68d67549d39ef98116b3c60599ccbc723d074cafa735010a6ff9085cbbc61a5d24e6bd4bd86b404f7b43a3ef3a07367c5eb7de85a03

test:
  secret_key_base: 20b2ac98b1553812e769532bedd87de7ba0465385510b8a3b8a9aa04ebe1b4f4ae05b233d36baaf36d1c46827cf2c77004b58cb00bd56968d27badb074912c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
